### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by WesBunton** [weiofcn/build-openssl-for-FIPS-Android#1]
The wget lines are causing a connection error when I attempt to run make. I can ping the IP's though...

**Comment by weiofcn** [comment]
@WesBunton  I just changed my VPS's system and all achives had been deleted in my VPS, so the link is invalid.

You may open the `Makefile` and modify the download link to the `openssl.org`, because I live in China and the `openssl.org` was been blocked by GFW.

Origin:
```
openssl-fips-2.0.12.tar.gz:
	#wget http://www.openssl.org/source/openssl-fips-2.0.12.tar.gz
	wget http://45.78.29.98/openssl-fips-2.0.12.tar.gz

openssl-1.0.2h.tar.gz:
	#wget http://www.openssl.org/source/openssl-1.0.2h.tar.gz
	wget http://45.78.29.98/openssl-1.0.2h.tar.gz
```

After:

```
openssl-fips-2.0.12.tar.gz:
	wget http://www.openssl.org/source/openssl-fips-2.0.12.tar.gz
	#wget http://45.78.29.98/openssl-fips-2.0.12.tar.gz

openssl-1.0.2h.tar.gz:
	wget http://www.openssl.org/source/openssl-1.0.2h.tar.gz
	#wget http://45.78.29.98/openssl-1.0.2h.tar.gz
```

**Comment by WesBunton** [comment]
I did that and it worked fine. Thanks for the quick response.
